### ISSUE TITLE
[Bug] [WorkFlow] The failed retry configuration does not take effect

### ISSUE THREAD

**Issue by welsh-wen** [apache/dolphinscheduler#11796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59044203/188563534-714005b6-9731-45de-b74f-eca4851a9f8d.png)
![image](https://user-images.githubusercontent.com/59044203/188564206-061f1245-d701-4640-a519-6ecd8f9c8c1e.png)

### What you expected to happen

The configuration takes effect

### How to reproduce

1.Create a shell workflow 
2.Configure the failure policy
3.Run the workflow and wait for it to fail 
4.Observe if it retries

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
i face a somewhat similar case, i will check itand try fix it. @SbloodyS

**Comment by SbloodyS** [comment]
> i face a somewhat similar case, i will check itand try fix it. @SbloodyS

Great. I've assigned to you.

**Comment by DarkAssassinator** [comment]
@welsh-wen did u configure the timeout setting? because the timeout setting will hang the retry process.

**Comment by DarkAssassinator** [comment]
if use configre the timeout and retry, it will cause a dead loop. 
because `TASK_STATE_CHANGE` state event will remove the taskProcessor
![image](https://user-images.githubusercontent.com/20518339/188891176-a09baf3c-6c48-4d9f-b311-8f64a872695a.png)
but later `TIME_OUT` state event will use this taskProcessor, it will throw a NPE:
![image](https://user-images.githubusercontent.com/20518339/188891628-9eab8a15-bc9c-417b-aefa-51d4018c7796.png)
And `WorkflowExecuteRunnable` will not remove this event if occur a Exception, so will keep a dead loop, then `WorkflowExecuteThreadPool` will keep print `The workflow has been executed by another thread`, this thread hang.

**Comment by caishunfeng** [comment]
close by #11864
