### ISSUE TITLE
[Bug] [Script] bin script didn't stop java process 

### ISSUE THREAD

**Issue by jamescheng16** [apache/dolphinscheduler#12417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use ./start-all and ./stop-all and ./install.sh, I found these script didn't kill java process correctly.
![Uploading Screen Shot 2022-10-18 at 16.23.55.png…]()

### What you expected to happen

when use ./install.sh or ./stop-all, the process will be killed automaticly

### How to reproduce

use script under this folder apache-dolphinscheduler-3.1.0-bin/bin

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songjianet** [comment]
Please confirm if the issue exists in 30x and dev, and re-upload the attached image.

**Comment by jamescheng16** [comment]
version 3.1.0 
![Screen Shot 2022-10-18 at 16 23 55](https://user-images.githubusercontent.com/4263914/196573994-d427df25-fd26-475f-a480-06ee65d08bb5.png)

**Comment by DarkAssassinator** [comment]
because current ds just use a pid file to save the process id, then kill it, so just will kill only one
![image](https://user-images.githubusercontent.com/20518339/196680149-c9ea6342-72ae-4c7d-a5f1-c61880f277ba.png)
so i want to refactor the ds cli
+ https://github.com/apache/dolphinscheduler/issues/12016

will use `ps -ef | grep "java" | grep "$DOLPHINSCHEDULER_HOME" | grep "$CLASS" | grep -v "grep" | awk '{print $2}' | xargs kill -9` to kill all service process.
