### ISSUE TITLE
[Bug] [Task-Group] The task group cannot release resources

### ISSUE THREAD

**Issue by Sky-Gu** [apache/dolphinscheduler#13107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a workflow is canceled or paused, resources in a task group cannot be released. The capacity of used resources in the task group is not updated, and the status of tasks in the task group queue is not updated.

### What you expected to happen

1. Workflow Various status operations can update the status of the task group normally, such as cancel, pause, and retry failure.
2. The task group UI interface can provide mandatory adjustments to the task group

 

### How to reproduce

1. Add a task group to a task
2. Define a large number of tasks in the workflow, such as 20 or more
3. Limit the concurrent execution of these tasks by task groups (this operation will form queued tasks in the task group queue)
4. Cancels or suspends execution of the workflow instance
5. The status of the workflow instance and task instance will be updated, but the task group and task group queue will not be updated
 
 

### Anything else

If the workflow instance is executing normally or the task itself fails to retry, the task group can be updated normally. If you manually cancel or pause in the UI, the task group will not update.
 
In this case, you need to passively manipulate the database to force changes to the t_ds_task_group and t_ds_task_group_queue, otherwise the task group will not recover.
 

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ProgrammerPlus1998** [comment]
I also encountered a similar problem. In order to reduce the peak load of the database, I configured multiple tasks into a task group in dolphinscheduler. Because of task failure, task suspension, etc., the task is actually no longer in the queue, but the number of used resources has not decreased. One, cause task blocking.
Solution: Move the blocked workflow out of this task group to restore the amount of resources. This method is tantamount to scooping up water and pouring it back to try to prevent the water from boiling. We don’t know when the problem will arise again. This function is very important for us. Very important, I hope this problem can be fixed, if you can't find the cause, I would like to help, thank you.

**Comment by ProgrammerPlus1998** [comment]
I also encountered a similar problem. In order to reduce the peak load of the database, I configured multiple tasks into a task group in dolphinscheduler. Because of task failure, task suspension, etc., the task is actually no longer in the queue, but the number of used resources has not decreased. One, cause task blocking.
Solution: Moving the blocked workflow out of this task group can restore the resource quantity. This method is tantamount to scooping up water and pouring it back to try to prevent the water from boiling. We don’t know when the problem will arise again. This function is very important for us. Very important, I hope this problem can be fixed, if you can't find the cause, I would like to help, thank you.

**Comment by ProgrammerPlus1998** [comment]
I also encountered a similar problem. In order to reduce the peak load of the database, I configured multiple tasks into a task group in dolphinscheduler. Because of task failure, task suspension, etc., the task is actually no longer in the queue, but the number of used resources has not decreased. resulting in task blocking.
Solution: Moving the blocked workflow out of this task group can restore the resource quantity. This method is tantamount to scooping up water and pouring it back to try to prevent the water from boiling. We don’t know when the problem will arise again. This function is very important for us. Very important, I hope this problem can be fixed, if you can't find the cause, I would like to help, thank you.
