### ISSUE TITLE
[Bug] [dolphinscheduler-api docker image] Version 3.1.3 of the api image front-end resource is missing, resulting in a white screen on the home page

### ISSUE THREAD

**Issue by qindisky** [apache/dolphinscheduler#13465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/guide/installation/kubernetes
k8s部署3.1.3版本成功后，访问首页出现白屏

### What you expected to happen

可以正常访问首页

### How to reproduce

按照https://dolphinscheduler.apache.org/zh-cn/docs/3.1.3/guide/installation/kubernetes说明，在k8s上部署服务
访问http://host/dolphinscheduler/ui/，出现白屏。
控制台报错信息，经排查
index.html使用/dolphinscheduler/ui/assets/index.13e03d85.js
在api的镜像中assets下，无index.13e03d85.js

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jieguangzhou** [comment]
Hi, @qindisky Would you be interested in fix it?

**Comment by cmd1024** [comment]
try this https://github.com/apache/dolphinscheduler/issues/13523#issuecomment-1437788399

**Comment by QuantumXiecao** [comment]
@SbloodyS @zhuangchong  This problem is due to the docker image located in apache repository is bad. 
I think we should redistribute docker image as quickly as possible.

@qindisky Current solution is you could build image using Dockerfile located in dolphin-scheduler source code using the following command: 
 docker build -t dolphin-api:latest -f src/main/docker/Dockerfile . (name dolphin-api just for test)

Emphasize again: The last "." is very important and it specifies the PATH for docker build context.

And I modify docker-compose.yaml like follows:
![image](https://user-images.githubusercontent.com/99702568/220874177-aaefb53e-0b64-40b0-93b1-17a61a24b586.png)
![image](https://user-images.githubusercontent.com/99702568/220874264-0360528e-361d-4678-aa42-be7054883cd8.png)
The dolphin login page display normally.

I think one possible problem is when building dolphinscheduler-api image it has used the previously generated front-end files(NPM would always change the resource name for each build process).
@SbloodyS  Please rebuild the image like what I did and redistribute it!
