### ISSUE TITLE
[Bug] [Admin Panel] Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by CNyezi** [apache/dolphinscheduler#13523]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

下载3.1.3版本的代码，尝试在本机使用docker-compose部署，已经部署成功。
但在打开admin页面时，页面空白，出现报错。
![image](https://user-images.githubusercontent.com/11954636/217133206-574a56ef-5c81-416d-83f3-93c5a5ccc757.png)
![image](https://user-images.githubusercontent.com/11954636/217133243-c0694beb-e949-4a41-a9e6-0cc0825bf000.png)
![image](https://user-images.githubusercontent.com/11954636/217133260-c11bff6e-495a-4abd-a755-a5188ec773c1.png)

### What you expected to happen

正常打开面板

### How to reproduce

3.1.3版本，根据docker-compose进行部署，即可复现。

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lzjxc** [comment]
Same here. I meet the same problem with k8s deploymentation.

**Comment by Vinke2** [comment]
我使用docker-compose部署也是一样的问题

**Comment by 794TD** [comment]
I have also meet this Problem

**Comment by showkeyjar** [comment]
+1

**Comment by cmd1024** [comment]
try this image
```
docker pull cccccmd/dolphinscheduler-api:3.1.3-fix-ui
```
You can also use the [Dockerfile ](https://hub.docker.com/r/cccccmd/dolphinscheduler-api)to build the image yourself

**Comment by QuantumXiecao** [comment]
@SbloodyS @zhongjiajie  This problem is due to the docker image located in apache repository is bad. 
I think we should redistribute docker image as quickly as possible.

Current solution is you could build image using Dockerfile located in dolphin-scheduler source code using the following command: 
 docker build -t dolphin-api:latest -f src/main/docker/Dockerfile . (name dolphin-api just for test)

Emphasize again: The last "." is very important and it specifies the PATH for docker build context.

And I modify docker-compose.yaml like follows:
![image](https://user-images.githubusercontent.com/99702568/220874177-aaefb53e-0b64-40b0-93b1-17a61a24b586.png)
![image](https://user-images.githubusercontent.com/99702568/220874264-0360528e-361d-4678-aa42-be7054883cd8.png)
The dolphin login page display normally.

I think one possible problem is when building dolphinscheduler-api image it has used the previously generated front-end files(NPM would always change the resource name for each build process).
@SbloodyS  Please rebuild the image like what I did and redistribute it!
