### ISSUE TITLE
[Bug] [style] maven-spotless plugin make some codes deleted

### ISSUE THREAD

**Issue by George-zqq** [apache/dolphinscheduler#13564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

maven-spotless plugin make some codes deleted

### when i build project , cause some error about spotless , and advice to run "mvn spotless:apply" first . The follow is some codes has been deleted 
![image](https://user-images.githubusercontent.com/23392145/218729145-d8bf81d9-82b8-42ae-84c1-1107b1a5b55e.png)
### Then compare the source and after spotless format
![image](https://user-images.githubusercontent.com/23392145/218728054-5947e448-7802-4879-9837-2930d7b4c7ff.png)

### How to reproduce

1. download source code and decompress
2. run command "./mvnw clean install -e -Prelease -Dzk-3.4"

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@EricGao888

**Comment by fuchanghai** [comment]
spotless will delete codes that Non-standard

**Comment by EricGao888** [comment]
@George-zqq This is expected behavior. For `wildcard imports`, `powermock imports`, `junit4 imports`, running `mvn spotless:apply` will directly remove related code. To avoid this, run `mvn spotless:check` ahead, fix `wildcard imports` with your IDE, then run `mvn spotless:apply` to fix the rest.

FYI: [spotless#649](https://github.com/diffplug/spotless/issues/649)
