### ISSUE TITLE
[Bug] [Module Name] After deploying dolphinscheduler with docker, the interface cannot be accessed

### ISSUE THREAD

**Issue by zhmingyong** [apache/dolphinscheduler#13592]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After deploying dolphinscheduler with docker, the interface cannot be accessed

### What you expected to happen

![c928cccd4e23b8bdc659012539ab7fc](https://user-images.githubusercontent.com/18400981/220276819-1d8fd915-400b-498b-8380-0bc79ce3765f.png)

### How to reproduce

1.pull sourcecode ，release version：3.1.3，3.0.4
2.docker-compose deploying
3.Access interface

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QuantumXiecao** [comment]
@zhmingyong Could you please explain it more specifically about "the interface cannot be accessed"?
I see your curling action has been successful. You mean you could not access the website through the browser?

**Comment by cmd1024** [comment]
#[13465](https://github.com/apache/dolphinscheduler/issues/13465) #[13523](https://github.com/apache/dolphinscheduler/issues/13523)
The js file named index.13e03d85.js does not exist.
You can repackage the dolphinscheduler-ui module and replace the ui directory in the container,but these changes will be lost after restarting the container.Also you can try to build a new image based on official image.
You can refer to the Dockerfile file on this [page](https://hub.docker.com/r/cccccmd/dolphinscheduler-api)

**Comment by QuantumXiecao** [comment]
@CCCCCMD  I see what you mean. Thanks for you feedback.

**Comment by QuantumXiecao** [comment]
@SbloodyS This problem is due to the docker image located in apache repository is bad. 
I think we should redistribute docker image as quickly as possible.

@zhmingyong Current solution is you could build image using Dockerfile located in dolphin-scheduler source code using the following command: 
 docker build -t dolphin-api:latest -f src/main/docker/Dockerfile . (name dolphin-api just for test)

Emphasize again: The last "." is very important and it specifies the PATH for docker build context.

And I modify docker-compose.yaml like follows:
![image](https://user-images.githubusercontent.com/99702568/220874177-aaefb53e-0b64-40b0-93b1-17a61a24b586.png)
![image](https://user-images.githubusercontent.com/99702568/220874264-0360528e-361d-4678-aa42-be7054883cd8.png)
The dolphin login page display normally.

I think one possible problem is when building dolphinscheduler-api image it has used the previously generated front-end files(NPM would change the js name for each build).
@SbloodyS  Please rebuild the image like what I did and redistribute it!
