### ISSUE TITLE
[Feature][] I want stop a process instance which state is "Serial wait".

### ISSUE THREAD

**Issue by ljjjjjjjjjjjjjjjjjjjjj** [apache/dolphinscheduler#13636]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description 
3.1.3version

![image](https://user-images.githubusercontent.com/22784075/226228404-77129981-2e02-4360-b190-33bae44b89b4.png)

 A process instance which state is "Serial wait" could not be stop.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JaayYoung** [comment]
I have same situation in 3.0 , copy a same workflow can be run. but it cant stop wait process.

**Comment by mxq-151** [comment]
any log for this issue?

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
actually，if you call the api with postman，here is a error code
{
    "code": "50006",
    "message": "the status of process instance xxxxx is WorkflowExecutionStatus{code=14, desc='serial wait'},Cannot perform STOP operation",
}

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
> any log for this issue?
actually，if you call the api with postman，here is a error code
{
"code": "50006",
"message": "the status of process instance xxxxx is WorkflowExecutionStatus{code=14, desc='serial wait'},Cannot perform STOP operation",
}

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
actually，if you call the api with postman，here is an error code
{
"code": "50006",
"message": "the status of process instance xxxxx is WorkflowExecutionStatus{code=14, desc='serial wait'},Cannot perform STOP operation",
}

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
create a process_definition with ”Serial wait“ Strategy， then start 2 instances ， make sure the 2th one start before the old one  finished, and the 2th one state will be ”Serial wait“ ，it can not be stop

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
I mean， this is a feature ，not a bug

**Comment by mxq-151** [comment]
> I mean， this is a feature ，not a bug

all task from the same process will block,even the master server restart, tasks still block.this bug  ocurr when the master failed and the task does not run to the end

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
1、only  process execute type = "Serial wait" ,all task from the same process will block.
![image](https://user-images.githubusercontent.com/22784075/226228501-e78deae2-09ef-4ab6-9def-1040624c783b.png)
![image](https://user-images.githubusercontent.com/22784075/226228539-1cce7bda-0c5d-4f63-b739-2c49e3c89eec.png)

2、if I stop the first instance，the，the second one will change state to running，then ，I can stop the second instance. My point is stop the second one when it is "Serial wait", so that we can stop the second one without stop the first one.
3、based on the current situation，I can stop the ”Serial wait“ instance this way ”Serial wait“ -> running -> stop.
but I want stop instance this way ”Serial wait“ -> stop.

**Comment by ljjjjjjjjjjjjjjjjjjjjj** [comment]
the point is I need stop all instance started before the instance I want stop，make the instance state chang from ”Serial wait“ to running，this is unreasonable.

**Comment by bullyb1911** [comment]
Experienced this issue in Psuedo Cluster Configuration. When all servers were stopped and then restarted minutes later using the packaged start/stop scripts, the server reboots and creates scheduled workflow instances even though pending jobs during the time the server was offline are no longer executing due to a Recover Serial wait state. The scheduler continues to schedule new executions while the pending job remains in a Recover Serial wait state. When the Recovery Serial Wait jobs eventually timeout, they terminate. There are roughly 400 scheduled jobs and each job has timeouts set to default. Cron Manage is offline to prevent new scheduled executions.  Users have to wait for the jobs to timeout before being able to run the workflow. I copied the workflow config and created a temporary project to get the required tasks to run. You can change the workflow config to parallel execution if this workflow can support such a setting to avoid this. This is Version 3.1.7.

**Comment by exitNA** [comment]
I have the same problem
