### ISSUE TITLE
[Bug] [Seatunnel Flink] --run-mode

### ISSUE THREAD

**Issue by jiaoyang3** [apache/dolphinscheduler#14376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Could not get job jar and dependencies from JAR file: JAR file does not exist: --run-mode

Flink Version : 1.15.4

I think the historical issue is ready to fix this issue. May I know which version will be launched？

### What you expected to happen

n/A

### How to reproduce

n/A

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lu952450497** [comment]
I encountered the same problem, and analysis found that it was due to the version issue used by seatunel. Dolphin relies on seatunel as 2.1. * or even earlier, while the latest version of seatunel is 2.3. *. This is caused by inconsistent start-seatunnel-flink.sh parameters in Flink. Waiting for updates
