### ISSUE TITLE
[Bug] [Resources] 3.2.0 The resource page displays "resource not exist"

### ISSUE THREAD

**Issue by l838224553** [apache/dolphinscheduler#15131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Upgrade to version 3.2.0. The resource page displays "resource not exist". Both "LOCAL" and "HDFS" have the same problem. The file path exists, the file exists, and upgrade-schema.sh and migration-resource.sh have been executed, successfully modifying the mysql library tables and successfully migrating the data.
The problem is shown below:
![image](https://github.com/apache/dolphinscheduler/assets/36987867/189d4cda-5dfa-4efe-9500-dbf690ca9452)
When I create a folder, both "Success" and "resource not exist" are displayed. The file is successfully created in the configured path, but is not displayed on the resource page, as shown in the following figure:
![image](https://github.com/apache/dolphinscheduler/assets/36987867/6a459bdf-83b5-4bec-9cfb-b8b9ba6067e6)

### What you expected to happen

I expect to be able to display resources properly and use the resource center properly

### How to reproduce

After the configuration is complete, the system starts and goes to the "Resources" page.

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Radeity** [comment]
Hi @l838224553 , can you provide some error logs?

**Comment by l838224553** [comment]
> Hi @l838224553 , can you provide some error logs?
There are no errors. I printed the debug log:
![image](https://github.com/apache/dolphinscheduler/assets/36987867/4172ec02-85a6-4539-910c-cdd7c68af412)

**Comment by Radeity** [comment]
Do you configure correct `resource.storage.upload.base.path`?

**Comment by l838224553** [comment]
> Do you configure correct `resource.storage.upload.base.path`?

Yes.It's configured correctly. And create folders will be prompted to "success", and the resource. The storage. The upload. Base. The path will generate the corresponding folder path, but will not display.
![image](https://github.com/apache/dolphinscheduler/assets/36987867/fc5a0388-4a25-481f-9a1f-a4f62439c136)

**Comment by l838224553** [comment]
> Do you configure correct `resource.storage.upload.base.path`?

Yes.It's configured correctly. In addition, the message "Success" is displayed when the folder is created, and the corresponding folder is generated in the "resource.storage.upload.base.path", but it is not displayed.
![image](https://github.com/apache/dolphinscheduler/assets/36987867/3e0bfd04-a3b8-4552-ace9-7cc253a13494)

**Comment by Radeity** [comment]
Please check server logs again, I can not reproduce this bug, seems sth wrong when querying resource list.

**Comment by l838224553** [comment]
> Please check server logs again, I can not reproduce this bug, seems sth wrong when querying resource list.

ok.Thanks.

**Comment by zhang-dz** [comment]
So, how to solve it ？

**Comment by xxd521** [comment]
So, how to solve it ？My resource.storage.upload.base.path=/data/dolphinscheduler/resources, it looks ok, My resource.storage.type=LOCAL is correct


[INFO] 2025-10-17 15:57:51.146 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[122] - Call GET:/dolphinscheduler/resources success, cost: 8ms
[INFO] 2025-10-17 15:57:58.545 +0800 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[107] - REQUEST TRACE_ID:19360957253632, LOGIN_USER:admin, URI:/dolphinscheduler/resources, METHOD:GET, HANDLER:org.apache.dolphinscheduler.api.controller.ResourcesController.queryResourceListPaging, ARGS:{searchVal=, pageNo=1, fullName=, pageSize=10, tenantCode=, type=FILE}
[ERROR] 2025-10-17 15:57:58.554 +0800 org.apache.dolphinscheduler.api.service.impl.ResourcesServiceImpl:[601] - Cannot invoke "org.apache.hadoop.fs.FileSystem.exists(org.apache.hadoop.fs.Path)" because "this.fs" is null Resource path: file:/data/dolphinscheduler/resources/default/resources/
java.lang.NullPointerException: Cannot invoke "org.apache.hadoop.fs.FileSystem.exists(org.apache.hadoop.fs.Path)" because "this.fs" is null
