### ISSUE TITLE
[BUG] datax bug

### ISSUE THREAD

**Issue by shaobo99** [apache/dolphinscheduler#2932]
1. 使用datax同步数据失败，却显示成功
2. datax同步数据可否增加自定义参数，用于同步增量数据

**Comment by xingchun-chen** [comment]
Which branch

**Comment by shaobo99** [comment]
1.3.0-release

**Comment by xingchun-chen** [comment]
1. I did not reproduce the problem, please confirm that the code is 1.3.0-release instead of dev, because the dev code may have this problem.
2. You can check the worker log, and confirm that the dataX environment variable is configured correctly in conf/env/dolphinscheduler_env.sh, and the dataX driver is added under lib

**Comment by zhongjiajie** [comment]
I would close this issue since no response from user and @xingchun-chen can not reproduce, you could reopen it if you have  further information
