### ISSUE TITLE
[Feature][*] Sql task extension, support multiple sql statement query

### ISSUE THREAD

**Issue by lgcareer** [apache/dolphinscheduler#3799]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*
**Background**
At present, the SQL task only supports the execution of one statement, that is, the `SQL Statement` in the  picture below currently only support one statement.
![image](https://user-images.githubusercontent.com/15651066/94260606-12c58080-ff63-11ea-9c46-c18280ddf5ce.png)

**Describe the feature**
Support multiple sql statement query
 - Design requirements:
1. Multiple SQL statements input by SQL Statement can be split into multiple statements;
2. Batch execution through jdbc
3. Support multiple data sources oracle, hive, postgresql, mysql

**Comment by Segun-Ogundipe** [comment]
Hi @lgcareer, @dailidong, @djkevincr, please assign me to the issue

**Comment by CalvinKirs** [comment]
> Hi @lgcareer, @dailidong, @djkevincr, please assign me to the issue

Looking forward to submitting pr

**Comment by Segun-Ogundipe** [comment]
Hi, @dailidong, @CalvinKirs, I have a few clarification questions on this feature.

I tested this by executing three statements and the three statements were executed
![image](https://user-images.githubusercontent.com/41447999/107632307-9bb92c00-6c66-11eb-8c90-372257dbbd76.png)

![image](https://user-images.githubusercontent.com/41447999/107632351-ad9acf00-6c66-11eb-8def-43b970f92719.png)

Is this not what this issue is supposed to fix or am I missing something?

**Comment by Segun-Ogundipe** [comment]
I think I understand it now. The SqlParameters and SqlBind data class gets the SQL statements in a single string instance no matter how many statements there is and then execute that. So this issue is to use JDBC batch processing to execute the statements for fast performance right?

Please let me know if my assumption is right.

**Comment by davidzollo** [comment]
> I think I understand it now. The SqlParameters and SqlBind data class gets the SQL statements in a single string instance no matter how many statements there is and then execute that. So this issue is to use JDBC batch processing to execute the statements for fast performance right?
> 
> Please let me know if my assumption is right.

yes, you are right

**Comment by Segun-Ogundipe** [comment]
Thank you
