### ISSUE TITLE
Multi-cluster support（多集群支持）

### ISSUE THREAD

**Issue by lipengbo2018** [apache/dolphinscheduler#427]
At present, our company has 2 big data clusters and wants to share the same scheduling system, hoping to provide support.
At present, only the configuration of different clusters can be tried to be used in different workers.

---
目前我们公司有2个大数据集群，想公用同一个调度系统，希望能提供支持。
目前只能尝试把不同集群的配置配到不同的worker中去使用。

**Comment by dailidong** [comment]
当前不支持多集群，你这个尝试是可以的，
如果只启动1个API Server的话，因为上传文件需要保存在hdfs上，所以如果多个worker同时工作的话，需要使用同一个hdfs配置，涉及到hadoop.properties, hdfs-site.xml，core-site.xml

如果启动2个API Server的话，可以每个Worker使用不同的hdfs配置

**Comment by silvermissile** [comment]
哇，我在找这个特性

**Comment by huanghaofan** [comment]
yes , I am find this feature too. 
multi-cluster is more useful by diffrent team  work together.

**Comment by BackFire** [comment]
这么有价值的特性，2年了，还没支持吗？

**Comment by SbloodyS** [comment]
I find deploying different yarn job in different yarn clusters is now supported in 2.0.1-release.

By deploying different worker in different clusters.And different clusters have different yarn.application.status.address in conf/common.properties.

Should we added this to doc in order to better let users to use ds in such circumstances? Such as best practice in multi yarn clusters.@dailidong

**Comment by zhongjiajie** [comment]
@SbloodyS Yeah, I think we should add this to our document. But we should find some place to keep it

**Comment by zhongjiajie** [comment]
Maybe we should put it in FAQ https://dolphinscheduler.apache.org/en-us/docs/release/faq.html. WDYT @SbloodyS @caishunfeng @lenboo

**Comment by SbloodyS** [comment]
> Maybe we should put it in FAQ https://dolphinscheduler.apache.org/en-us/docs/release/faq.html. WDYT @SbloodyS @caishunfeng @lenboo

Sounds good to me. I will submit a PR to this.

**Comment by zhongjiajie** [comment]
Closed by apache/dolphinscheduler-website#692
