### ISSUE TITLE
[Bug][server] failoverWorker 容错

### ISSUE THREAD

**Issue by whw02** [apache/dolphinscheduler#4757]
分支：dev
测试中发现dolphinscheduler-server模块中关于ZKMasterClient中failoverWorker方法中查询需要容错的任务实例时，入参workerHost并不是ip地址加端口号
![image](https://user-images.githubusercontent.com/57203550/107371380-31e23a80-6b1f-11eb-87a8-c2974eafc447.png)

根据打印的日志显示如下:
![image](https://user-images.githubusercontent.com/57203550/107371489-4c1c1880-6b1f-11eb-96cd-70f78415b3a5.png)

从而导致查询不到数据库中的需要容错任务实例，不能完成容错机制。同理failoverMaster也存在这样的问题。

不知是否是我配置问题，还是什么原因。谢谢

**Comment by davidzollo** [comment]
as a global project, please update/add title and description in English, thx

**Comment by zhuangchong** [comment]
Worker failover does have problems, while Master failover is normal,I will fix the problem.

![image](https://user-images.githubusercontent.com/37063904/107961634-22606700-6fe1-11eb-986a-b2255938a317.png)

**Comment by chengshiwen** [comment]
@dailidong @zhuangchong @CalvinKirs 
This issue is caused by calculating the warm-up time of load balancing, see
- [code 1](https://github.com/apache/incubator-dolphinscheduler/blob/5f40fce1f5544baffe34356e4244aaf0b364fd83/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry.java#L162)
- [code 2](https://github.com/zt-1997/incubator-dolphinscheduler/blob/8aae5b599b9f7437e4f1e0dd365d62f86d9f03b1/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/WorkerGroupService.java#L170)

Similar problems always exist wherever the timestamp suffix needs to be removed.

**Comment by CalvinKirs** [comment]
Maybe host + timestamp is used in business use (it may be used in too many scenarios, we don't need to distinguish it), but in the final interaction with the database, do a layer of conversion, (remove the timestamp) what do you think.

**Comment by zhuangchong** [comment]
> Maybe host + timestamp is used in business use (it may be used in too many scenarios, we don't need to distinguish it), but in the final interaction with the database, do a layer of conversion, (remove the timestamp) what do you think.

I think it's OK to do that
