### ISSUE TITLE
[Improvement][Flink] Flink tasks do not support Generic CLI mode

### ISSUE THREAD

**Issue by syb853553110** [apache/dolphinscheduler#4924]
**Describe the question**
(1)Flink deployment modes currently not supported：yarn-per-job

(2) Some parameters cannot be selected 

**What are the current deficiencies and the benefits of improvement**

It is more convenient to submit Flink tasks

**Which version of DolphinScheduler:**
 -[1.3.5-release]

**Describe alternatives you've considered**
（1）Add Options for Generic CLI mode:
-t,--target <arg> For the "run" action the currently available
                           targets are: "remote", "local", "kubernetes-session",
                           "yarn-per-job", "yarn-session". For the
                           "run-application" action the currently available
                           targets are: "kubernetes-application",
                           "yarn-application".
（2）It is recommended to add a few parameters:
-d,--detached 
-p,--parallelism <parallelism> 
-s,--fromSavepoint <savepointPath>
--allowNonRestoredState

**Comment by chengshiwen** [comment]
@syb853553110 `yarn-per-job` mode is supported in Flink task, since it's just equivalent to `yarn-cluster` mode

(1) `Generic CLI` mode you said does not support, because the mode is just supported from flink 1.10.
`Attention`: `yarn-per-job` in `Generic CLI` mode is is just equivalent to `yarn-cluster` mode.
We will consider to support `Generic CLI` mode in future.

(2) You can specific the following options in `Option parameters`:
```
-d,--detached
-p,--parallelism
-s,--fromSavepoint
--allowNonRestoredState
```

(3) We also have added `-p,--parallelism` as a new parameter Input in #4937

**Comment by chengshiwen** [comment]
@syb853553110 Could you please rename the title to `[Improvement][Flink] Flink tasks do not support Generic CLI mode`? Thx so much!
`

**Comment by CalvinKirs** [comment]
close by #4937
