### ISSUE TITLE
The workflow instance cannot be operated after being suspended. The task is still running

### ISSUE THREAD

**Issue by VSMDD** [apache/dolphinscheduler#5274]
Unable to operate after the task has been paused，The task is still running
![image](https://user-images.githubusercontent.com/31095506/114671448-b414f800-9d36-11eb-9e0e-63b3bd13d59d.png)
![image](https://user-images.githubusercontent.com/31095506/114671521-c55e0480-9d36-11eb-909d-3a82d4db6a13.png)
![image](https://user-images.githubusercontent.com/31095506/114671577-d3138a00-9d36-11eb-8d4a-0bca824970d1.png)

**Comment by xingchun-chen** [comment]
After pausing, you need to wait for the current task to execute successfully before pausing the workflow. Since you have written while (1), the task will be executed all the time. It is recommended that you directly update the database table t_ds_ process_ instance.state=6 ,t_ds_task_instance.state=6

**Comment by VSMDD** [comment]
thank you
