### ISSUE TITLE
view log no output

### ISSUE THREAD

**Issue by 18610028899** [apache/dolphinscheduler#5368]
there is nothing when click view output。 ds dockers are running on 2 machine， 1 for api， 1 for worker，master， alert 

**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by ruanwenjun** [comment]
You can get more error information from `api`, maybe you need to start the `LoggerServer`.

**Comment by chengshiwen** [comment]
@18610028899 How did you start the services by docker on 2 machines? And could you give us more details?

**Comment by 18610028899** [comment]
api-server run  on machine a, and the others run  on machine b by docker. I can't find logserver

**Comment by chengshiwen** [comment]
@18610028899 `logger-server` runs in the worker container.

Due to the `bridge` network used by docker by default, containers cannot communicate directly on multiple different hosts. You should use an `overlay` network, please refer to https://docs.docker.com/network/overlay/

I will give the detailed steps about the deployment on multiple hosts in future

Currently, it is recommended to use `docker-compose` to deploy on the same machine, please refer to https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/docker-deployment.html

**Comment by chengshiwen** [comment]
Close since no updates for long time
