### ISSUE TITLE
[1.3.6][dolphinscheduler-api] DataSourceController create mysql version 8.0 fail

### ISSUE THREAD

**Issue by cpbeast** [apache/dolphinscheduler#5495]
![image](https://user-images.githubusercontent.com/41602866/118612138-0fcc1880-b7f0-11eb-9bcf-8465a43867bf.png)
It is only compatible with MySQL version 5.7, but not version 8.0

**Comment by ruanwenjun** [comment]
@cpbeast  Can you describe your operation and provide the error log? I think this can work well with MySQL 8.0. 
I have tested on MySQL 8.0.22, it will print a warning log, this is caused by ssl, if you also meet this problem, you can try to set  `useSSL=false`
https://github.com/apache/dolphinscheduler/blob/bc22ae7c91c9cbd7c971796ba3a45358c2f11864/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/datasource/mysql/MysqlDatasourceProcessor.java#L54

**Comment by cpbeast** [comment]
> Can you describe your operation and provide the error log? I think this can work well with MySQL 8.0.
> I have tested on MySQL 8.0.22, it will print a warning log, this is caused by ssl, if you also meet this problem, you can try to set `useSSL=false`

![image](https://user-images.githubusercontent.com/41602866/118751646-3e033400-b894-11eb-9409-a54669ef46c0.png)
I just started to learn. I used docker compose deployment on MAC, and there was no change. From the log, it was the driver problem of connecting to MySQL. Version 8.0 should be com.mysql.cj.jdbc.driver

**Comment by ruanwenjun** [comment]
@cpbeast I think this is caused by the driver missing, have you downloaded the MySQL connector lib? Maybe you can follow the tip in `How to support MySQL` https://dolphinscheduler.apache.org/en-us/docs/latest/user_doc/docker-deployment.html

**Comment by cpbeast** [comment]
I understand. After downloading the source code, I should modify < mysql. Connector. Version > 8.0.21 < / MySQL. Connector. Version >. When loading the driver, I should change com.mysql.jdbc.driver to com.mysql.cj.jdbc.driver,then build docker images and deployed using docker compose
![image](https://user-images.githubusercontent.com/41602866/118754421-9db00e00-b899-11eb-9b4a-91609debdcfc.png)
![image](https://user-images.githubusercontent.com/41602866/118754449-abfe2a00-b899-11eb-9b12-57ea7fe21ea4.png)

**Comment by ruanwenjun** [comment]
@cpbeast I think you need to download the connector lib
![image](https://user-images.githubusercontent.com/22415594/118758776-42cee480-b8a2-11eb-8793-536547fb1c5e.png)

Of course, you can choose a higher version of the connector, but what I want to say is that the current version can also work. It may be a good idea to provide version options when adding data sources, because sometimes different versions of Driver may not be compatible.

**Comment by cpbeast** [comment]
> @cpbeast I think you need to download the connector lib
> ![image](https://user-images.githubusercontent.com/22415594/118758776-42cee480-b8a2-11eb-8793-536547fb1c5e.png)
> 
> Of course, you can choose a higher version of the connector, but what I want to say is that the current version can also work. It may be a good idea to provide version options when adding data sources, because sometimes different versions of Driver may not be compatible.

大哥，你是上海的吗，你刚刚说的项目跑起来使用mysql的数据库吧，我是使用postgresql
![image](https://user-images.githubusercontent.com/41602866/118764134-98f45580-b8ab-11eb-95f1-9ccaac477e05.png)

在页面 创建数据源，添加mysql数据源的时候，报错，看日志说是驱动的问题
如果自己修改了源码，然后build镜像，取个自己的tag，然后使用docker-compose部署，应该可以吧
