### ISSUE TITLE
server down will send repetitive message

### ISSUE THREAD

**Issue by wangxj3** [apache/dolphinscheduler#5525]
The master and worker will listen to other master or worker services down from zk, and will send message notifications, but this message  will send one for each monitored service, so repeat.
For example, I have 3 masters and 3 workers, and one of the masters is down. The remaining five services will insert an alert data 
 in the database.
I haven't a good plan to fix this issue ,shoule we  consider the influence of normal version iterations?

**Comment by ruanwenjun** [comment]
@wangxj3 Yeal, I also noticed this problem, this caused by each instance will listen the node path in zookeeper. 
~~One possible solution is to get the lock on zookeeper when insert the instance crash alert.~~
Can we think each instance should save at most one unsent instance alert in database?

**Comment by wangxj3** [comment]
> 
> 
> @wangxj3 Yeal, I also noticed this problem, this caused by each instance will listen the node path in zookeeper.
> ~One possible solution is to get the lock on zookeeper when insert the instance crash alert.~
> Can we think each instance should save at most one unsent instance alert in database?
---Can we think each instance should save at most one unsent instance alert in database?
Yes,this we will do something in alert .Do you have a dateil plan?
---And
The solution with lock on zookeeper can resove this issue.How ablut that,if we can get the time of server down ,insert this time to t_ds_alert ,this time is the PRIMARY KEY,so other server will fail to insert database.

**Comment by ruanwenjun** [comment]
@wangxj3 I think it is hard to get the exact time when the server down, the time that each instance gets this event may be different.
Use lock on zookeeper does not seem to be a good solution for this issue, because some instances may get this event late.
The best solution may be when we insert to the t_ds_alert table, check whether there is the same content in the database for sending, the SQL like below
```sql
INSERT INTO t_ds_alert(instance, user, item) 
    SELECT xx, xxx, xxxx FROM t_ds_alert
        WHERE NOT EXISTS (SELECT * FROM t_ds_alert WHERE content ='' AND alert_status = WAIT_EXECUTION)
```
I didn't test this SQL, but this should be work.
In this way, there will be only one unsent alert for each instance in the database. But I think this is reasonable.

**Comment by CalvinKirs** [comment]
This is indeed a question that can be improved. Can anyone submit a PR for this?
