### ISSUE TITLE
[Bug][Master] ServerNodeManager WorkerGroupListener capture data change and get data failed

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5578]
**To Reproduce**

Both the two master servers have the following logs:

```
ServerNodeManager WorkerGroupListener capture data change and get data failed
```

**Expected behavior**

Bug fixed

**Screenshots**

![image](https://user-images.githubusercontent.com/4902714/120416055-1e3d3700-c38f-11eb-9c5e-813de3e73c65.png)
![image](https://user-images.githubusercontent.com/4902714/120416065-2301eb00-c38f-11eb-90ab-46117fdeaa09.png)
![image](https://user-images.githubusercontent.com/4902714/120416083-2a28f900-c38f-11eb-87be-151001706bc4.png)
![image](https://user-images.githubusercontent.com/4902714/120416097-2e551680-c38f-11eb-9d73-fce3736d0d8a.png)
![image](https://user-images.githubusercontent.com/4902714/120416099-30b77080-c38f-11eb-8c19-b71894ca7b1e.png)

**Which version of Dolphin Scheduler:**
 -[1.3.6]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ruanwenjun** [comment]
This does happen, if the two master crash at the same time(If there is only one master, it's easier to reproduce).
Because currently we have multiple listeners that will listen the node changes.
https://github.com/apache/dolphinscheduler/blob/cc9e5d5d34fcf2279b267cca7df37a9e80eeba07/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/zk/ZKMasterClient.java#L217-L228
If this listener exeucte first, it will remove the node, and will cause Master stop, and execute QuartzExecutors.shutdown method to close the datasource.

The main reason is that the listener has no order.

Here is a related issue #5491 and related pr #5497

**Comment by CalvinKirs** [comment]
close by #5919
