### ISSUE TITLE
[Feature][Task] Task can run on kubernetes

### ISSUE THREAD

**Issue by geosmart** [apache/dolphinscheduler#5648]
the storage layer we use minio deploy in k8s,

the compute layer now use yarn, we have to ops yarn(cdh) and k8s both.

so we want to run spark or flink task on k8s.

ref: [Kubernetes Apache Spark](https://www.slidestalk.com/AliSpark/KubernetesApacheSpark30159)

**Comment by CalvinKirs** [comment]
Very good idea, I am starting the design of this piece, maybe we can discuss and exchange together. My plan is that the resource scheduling platform and tasks belong to two different plugin modules.
If the task supports it, then it can choose to submit to any resource scheduling platform (which will be in the form of a plugin), such as yarn or k8s.

For us, we really just need to get the task results from the resource scheduling platform.

**Comment by blackberrier** [comment]
Can I join this discussion? Recently I am working on this part as well. 
I have already done some work about submitting tasks to kubernetes. Now I have completed spark and flink tasks, including submitting, killing, and state querying . This part is simple because spark and flink architecture have done a lot for us, we can simply use `spark-submit` or `flink run` to realize. And Java\Python tasks WIP. As to integrating to dolphinscheduler, I just add some configurations and rewrite `SparkArgsUtils.java` and other class. My method is simple now, and we can discuss a more elegant way.
And one more thing, I think storage layer matters a lot, because if we use k8s instead of yarn, we can't use hdfs probably.

**Comment by CalvinKirs** [comment]
> Can I join this discussion? Recently I am working on this part as well.
> I have already done some work about submitting tasks to kubernetes. Now I have completed spark and flink tasks, including submitting, killing, and state querying . This part is simple because spark and flink architecture have done a lot for us, we can simply use `spark-submit` or `flink run` to realize. And Java\Python tasks WIP. As to integrating to dolphinscheduler, I just add some configurations and rewrite `SparkArgsUtils.java` and other class. My method is simple now, and we can discuss a more elegant way.
> And one more thing, I think storage layer matters a lot, because if we use k8s instead of yarn, we can't use hdfs probably.

Of course you can, you are very welcome. I'm currently working on the data source SPI and the resource storage SPI, and when those two are complete we can get started. Currently, the Task plugin and interacts more closely with these two modules. Let me start the email discussion, if you haven't subscribed to the email yet, you can refer to this document to subscribe (https://dolphinscheduler.apache.org/zh-cn/community/development/subscribe.html)

**Comment by CalvinKirs** [comment]
> > Can I join this discussion? Recently I am working on this part as well.
> > I have already done some work about submitting tasks to kubernetes. Now I have completed spark and flink tasks, including submitting, killing, and state querying . This part is simple because spark and flink architecture have done a lot for us, we can simply use `spark-submit` or `flink run` to realize. And Java\Python tasks WIP. As to integrating to dolphinscheduler, I just add some configurations and rewrite `SparkArgsUtils.java` and other class. My method is simple now, and we can discuss a more elegant way.
> > And one more thing, I think storage layer matters a lot, because if we use k8s instead of yarn, we can't use hdfs probably.
> 
I remember that it is possible, HDFS is just a storage, it is not necessary, but we can still use it (when flink submit task on k8s)
> Of course you can, you are very welcome. I'm currently working on the data source SPI and the resource storage SPI, and when those two are complete we can get started. Currently, the Task plugin and interacts more closely with these two modules. Let me start the email discussion, if you haven't subscribed to the email yet, you can refer to this document to subscribe ()

**Comment by geosmart** [comment]
when use spark on k8s(spark 2.4.8 ), I make a list what we need to do:
1. change dolphinscheudler from hdfs to minio;
2. change kill yarn job by applicationId(both in worker and master)  to stop spark-driver-pod.
3. without yarn log aggregate, have to manual aggregate spark executor log by ELK or some other tool.
4. change the spark job monitor way from yarn-rest-api to k8s-api;
5...

@blackberrier anything else please do some complement ?

I'm doing a POC to migrate from yarn to k8s

**Comment by blackberrier** [comment]
> when use spark on k8s(spark 2.4.8 ), I make a list what we need to do:
> 
> 1. change dolphinscheudler from hdfs to minio;
> 2. change kill yarn job by applicationId(both in worker and master)  to stop spark-driver-pod.
> 3. without yarn log aggregate, have to manual aggregate spark executor log by ELK or some other tool.
> 4. change the spark job monitor way from yarn-rest-api to k8s-api;
>    5...
> 
> @blackberrier anything else please do some complement ?
> 
> I'm doing a POC to migrate from yarn to k8s

@geosmart You have considered this issue comprehensively, I think maybe we can add the following one?
1. build spark docker images, and when submitting applications let user choose or fill the docker name and version parameters. And other parameters as well?

Ps,  maybe we should consider more about your 3rd and 4th point. In yarn side, we get yarn application id from logs and filter pattern like "application_xxxxxxxxxx_yyyy", and get application state through yarn-rest-api. As to kubernetes, we don't have application pattern like yarn, maybe we should add some pattern to pods or something?

Ps, as we discussed through email, maybe this issue is not that hurry? @CalvinKirs

**Comment by chengshiwen** [comment]
@geosmart @blackberrier 
I think the following things should be considered:
1. extend `SparkArgsUtils.java` and `spark.vue`
2. adapt to get the spark job state using `namespace` and `<driver-pod-name>`, instead of calling `isSuccessOfYarnState` and `yarn rest api`
3. adapt to kill spark job using `namespace` and `<driver-pod-name>`, instead of `yarn application -kill`
4. check the spark application name that is specified by `spark.app.name` or the `--name` argument whch must consist of lower case alphanumeric characters, -, and . and must start and end with an alphanumeric character

Things that should not be done by us:
1. change dolphinscheudler from hdfs to minio (dependencies hosted in remote locations like HDFS or HTTP servers should be solved by user, like using pvc to pre-mount them)
2. yarn log aggregation (third-party framework should solve it)
3. build spark docker images (not our duty, user will customize the image to match an individual application’s needs)

**Comment by chengshiwen** [comment]
BTW, only spark is discussed, it seems that the title needs to be updated to remove flink

**Comment by geosmart** [comment]
@chengshiwen @blackberrier  thanks for your advice, and try  to do a small stage conclusion.

when `provide k8s to run spark app`, we need do:

# environment prepare
* build spark on k8s docker image for special spark version.
* collect spark driver and executor log by `elk` or som other stack
* collect metrics and monitor spark cluster by `promethus`　or som other stack

# ds-frontend
* `deployMode`: k8s,yarn,local
* `sparkVersion`: support custom version when deployed with `k8s`

# ds-backend
## submit spark app (worker)
* spark-submit: using `spark-submit` cmd to submit a app
* [spark-on-k8s operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator): using `kubectl apply -f <updated YAML file>` to submit a app

## check spark app status(worker)
* uing `kubectl describe sparkapplications <name> ` by  `spark-on-k8s operator`  

## kill spark app(master and worker)
* using `namespace` and `<driver-pod-name>` (killing driver pod is actually the way to stop the Spark Application during the execution）
* uing `kubectl delete <name> ` by  `spark-on-k8s operator`

**Comment by Wilson-BT** [comment]
> @chengshiwen @blackberrier thanks for your advice, and try to do a small stage conclusion.
> 
> when `provide k8s to run spark app`, we need do:
> 
> # environment prepare
> * build spark on k8s docker image for special spark version.
> * collect spark driver and executor log by `elk` or som other stack
> * collect metrics and monitor spark cluster by `promethus`　or som other stack
> 
> # ds-frontend
> * `deployMode`: k8s,yarn,local
> * `sparkVersion`: support custom version when deployed with `k8s`
> 
> # ds-backend
> ## submit spark app (worker)
> * spark-submit: using `spark-submit` cmd to submit a app
> * [spark-on-k8s operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator): using `kubectl apply -f <updated YAML file>` to submit a app
> 
> ## check spark app status(worker)
> * uing `kubectl describe sparkapplications <name> ` by  `spark-on-k8s operator`
> 
> ## kill spark app(master and worker)
> * using `namespace` and `<driver-pod-name>` (killing driver pod is actually the way to stop the Spark Application during the execution）
> * uing `kubectl delete <name> ` by  `spark-on-k8s operator`

I had participated in doing the same things in streamx for flink on  k8s. PerHaps I can join your works to Rich the Features of Dolphinscheduler. For flink on k8s,we can use s3 to be pvc, and all resources can mount on it. for spark on k8s, we use client -mode to avoid introduce  elk.

**Comment by dailidong** [comment]
> > @chengshiwen @blackberrier thanks for your advice, and try to do a small stage conclusion.
> > when `provide k8s to run spark app`, we need do:
> > # environment prepare
> > 
> > * build spark on k8s docker image for special spark version.
> > * collect spark driver and executor log by `elk` or som other stack
> > * collect metrics and monitor spark cluster by `promethus`　or som other stack
> > 
> > # ds-frontend
> > 
> > * `deployMode`: k8s,yarn,local
> > * `sparkVersion`: support custom version when deployed with `k8s`
> > 
> > # ds-backend
> > ## submit spark app (worker)
> > 
> > * spark-submit: using `spark-submit` cmd to submit a app
> > * [spark-on-k8s operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator): using `kubectl apply -f <updated YAML file>` to submit a app
> > 
> > ## check spark app status(worker)
> > 
> > * uing `kubectl describe sparkapplications <name> ` by  `spark-on-k8s operator`
> > 
> > ## kill spark app(master and worker)
> > 
> > * using `namespace` and `<driver-pod-name>` (killing driver pod is actually the way to stop the Spark Application during the execution）
> > * uing `kubectl delete <name> ` by  `spark-on-k8s operator`
> 
> I had participated in doing the same things in streamx for flink on k8s. PerHaps I can join your works to Rich the Features of Dolphinscheduler. For flink on k8s,we can use s3 to be pvc, and all resources can mount on it. for spark on k8s, we use client -mode to avoid introduce elk.

good job, I want to get to know you and make a connection.
Please add my mail(lidongdai@apache.org) or wechat(taskflow), when added , please tell me your github id, thx

**Comment by Littlehhao** [comment]
Is this function implemented?
