### ISSUE TITLE
[Improvement][Module Name] Meta database storage mode recommendations

### ISSUE THREAD

**Issue by k9flame** [apache/dolphinscheduler#5675]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/community/development/issue.html when describe an issue.*

**Describe the question**
I am in the process of using DS, because the data rectification, I put some data deleted, but the original workflow still use the data source, so I need to each point to change the data source, the vast number of workflow, so I want to by direct changes to the source database data source in the form of a one-time change, but I found some problems.I'm looking at t_ ds_ task_ Instance, we found that all datasource IDs are stored in JSON, 

**What are the current deficiencies and the benefits of improvement**
which is obviously not conducive to batch change. Therefore, I wonder if datasource ID can be stored in a separate field. Of course, this is just my idea. I don't know what the developers are thinking.Please forgive me if I am wrong.

**Which version of DolphinScheduler:**
 -[1.3.5-preview]

**Comment by ruanwenjun** [comment]
@k9flame Yes, some attribute is store in database as JSON string, this is due to the fact that we are not currently using a document-based database. It is difficult to expand all properties to store in database.

According to you, do you need to modify the historical execute instance? It seems pointless to modify the datasource of a historical process instance. If you want to batch change the current data source in process definition, I think this is worth discussing.

**Comment by jasonlnk** [comment]
This is a problem。If the data source of the JSON file changes, a function is needed to change the data source information in the JSON file synchronously when the data source changes.
I have an idea to store the content of the JSON file in the database in the form of text. When running, it will be extracted from the database to generate a JSON file for job. When the data source changes, we just need to replace the field of the JSON file, which is what we do now.
