### ISSUE TITLE
[Question] Environment of Python Task is different from that of real worker container

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#5685]
My DS system is setup by Docker.
When I ran like this in a PythonTask, I found that env is different from what i got in the docker container of worker.
![image](https://user-images.githubusercontent.com/84900511/123031551-04839280-d417-11eb-941d-971d9231422c.png)
This is what env showed by the **Python Task.**
![image](https://user-images.githubusercontent.com/84900511/123030919-14e73d80-d416-11eb-949d-2ab6cfc349e1.png)
And this is what env showed by execute `os.system("env")` or `os.environ` **directly in the container of worker**.
![image](https://user-images.githubusercontent.com/84900511/123031136-6394d780-d416-11eb-8186-7e0a86e2304e.png)

I don't know why they are totally different, especially the Variable 'PATH'. I thought that docker container is exactly where python executes script. So i am confused
 
**Which version of DolphinScheduler:**
 -[1.3.6-release]

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn It is because of the tenant? It seems that you use the tenant `2` to execute the `PythonTask`. You can try to use user `2` to execute os.system("env") or os.environ directly in the container of worker, and then compare the result.

**Comment by wangmingzhiJohn** [comment]
@ruanwenjun You are right. But how can I make the ENV settings available when I use tenant to execute the python script. I can't access the hadoop because some Variable not in PATH

**Comment by ruanwenjun** [comment]
@wangmingzhiJohn I guess the hadoop is just set up for special users, you can try to add it to your tenant user's PATH.

**Comment by chengshiwen** [comment]
@wangdazhong001 Under different user, the result of `env` is different. Regardless of whether it is in the docker container, the same thing happens in linux on the host machine. The richer environment variables directly in the container of worker occur under `roor` user.  While the environment variables from the python task occur under the user whose id is 2.

Since the python script does not execute `source /opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh`, the python task cannot read the environment variables in this file.

If you want to access the environment variables from `/opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh`, there are four solutions:

1. `open('/opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh', 'r')` and parse it
2. Use `python-dotenv`
3. Use the following code:
```python
import os
import pprint
import shlex
import subprocess

command = shlex.split("env -i bash -c 'source /opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh && env'")
proc = subprocess.Popen(command, stdout = subprocess.PIPE)
for line in proc.stdout:
  (key, _, value) = line.partition("=")
  os.environ[key] = value
proc.communicate()

pprint.pprint(dict(os.environ))
```
4. Use shell task instead of python task
```shell
source /opt/dolphinscheduler/conf/env/dolphinscheduler_env.sh
python /path/to/your_python_script.py
```

**Comment by wangmingzhiJohn** [comment]
@chengshiwen  @ruanwenjun Thank for your advise, I will try it.

**Comment by chengshiwen** [comment]
Close since it has been replied
