### ISSUE TITLE
[Question] What's the relation between these two sql files

### ISSUE THREAD

**Issue by wangmingzhiJohn** [apache/dolphinscheduler#6002]
I found two sql files. One is dolphinscheduler_mysql.sql, the other is dolphinscheduler_ddl.sql. According to the code of script/create-dolphinscheduler.sh, it will use dolphinscheduler_ddl.sql to init database. However, I check the mysql database and found that the current tables in database are different from which created by dolphinscheduler_ddl.sql. Those tables are same as which defined in dolphinscheduler_mysql.sql.
Like below, their tables are different according to names.
![image](https://user-images.githubusercontent.com/84900511/129874475-72a1838e-e097-4313-9b6e-f96db488192d.png)
![image](https://user-images.githubusercontent.com/84900511/129874542-3eb58797-504d-4732-8969-c6162012027c.png)
So, what the relationship between two files? 

**Which version of DolphinScheduler:**
 -[1.3.6-release]

**Comment by davidzollo** [comment]
good issue, 
create-dolphinscheduler.sh will use dolphinscheduler_ddl.sql and then it will run a java program
```
CLASS=org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler

exec_command="$DOLPHINSCHEDULER_OPTS -classpath $DOLPHINSCHEDULER_CONF_DIR:$DOLPHINSCHEDULER_LIB_JARS $CLASS"

cd $DOLPHINSCHEDULER_HOME
$JAVA_HOME/bin/java $exec_command
```
this java program `CreateDolphinScheduler` will first use dolphinscheduler_ddl.sql as a basis, and then upgrade to the version for the corresponding database.

you also can execute dolphinscheduler_mysql.sql  directly instead of the create-dolphinscheduler.sh,
by the way, the create-dolphinscheduler.sh is used to maintain backward compatibility, You will find that DolphinScheduler also uses this sh file when upgrading to the new version

**Comment by wangmingzhiJohn** [comment]
@dailidong  Thanks for your reply. It's very useful.
