### ISSUE TITLE
[Bug] [UI]  api error in dependent task.

### ISSUE THREAD

**Issue by lenboo** [apache/dolphinscheduler#6236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 create dependent task failed.

![image](https://user-images.githubusercontent.com/29528966/133639719-bdc05122-0ab5-4744-9ceb-58cae0b51020.png)

### What you expected to happen

create dependent successfully.

### How to reproduce

1. login as a non admin user
2. create a new project
3. create a new process with dependent task 
4. create dependent task failed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by devosend** [comment]
I will fix this bug.

**Comment by wangyizhi1** [comment]
The reason for this problem is that the front end should obtain actionable projects through `GET projects/created-and-authed` instead of `GET projects/list`. The `projects/list` interface will return all projects, including those for which the current user does not have permission. When an unauthorized projectCode is passed in, it is reasonable for the backend to throw an error on the `GET projects/{projectCode}/process-definition/all` interface.
In the old version, there may be ultra vires.

=====

这个问题的原因在于，前端应该通过 `GET projects/created-and-authed` 而不是 `GET projects/list` 来获取可以操作的projects。`GET projects/list` 接口会返回所有的项目，包括当前用户没有权限的。
当传入未授权的projectCode时，后端在 `GET projects/{projectCode}/process-definition/all` 接口抛出错误是合理的。
老版本中这里可能存在越权问题。

Fixed in #6238

**Comment by brave-lee** [comment]
Good job
