### ISSUE TITLE
[Bug] [UT] UT failed in DAO module

### ISSUE THREAD

**Issue by ruanwenjun** [apache/dolphinscheduler#6336]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run the UT in `TaskInstanceMapperTest`, it failed.
The `process_definition_code` is null.

```java
### SQL: INSERT INTO t_ds_process_instance  ( warning_group_id,   timeout,          executor_id,     max_try_times, tenant_id,   command_param, run_times, process_definition_version )  VALUES  ( ?,   ?,          ?,     ?, ?,   ?, ?, ? )
### Cause: java.sql.SQLException: Field 'process_definition_code' doesn't have a default value
; Field 'process_definition_code' doesn't have a default value; nested exception is java.sql.SQLException: Field 'process_definition_code' doesn't have a default value
```

### What you expected to happen

UT execute success.

### How to reproduce

Execute TaskInstanceMapperTest.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricPyZhou** [comment]
@ruanwenjun When I run `TaskInstanceMapperTest`, the failed test showed the log:
![image](https://user-images.githubusercontent.com/26387900/134845497-f807b393-60d7-4796-9ba5-d7536f2699af.png)

Which is a different one, btw I'm on the latest dev branch.

Based on my error log, I went to the table and indeed did not find any column named `process_definition_version`

Can you also double-check on your local environment so that we can confirm that this failure is reproducible?

PS: I rerun `CreateDolphinScheduler` after pulling the lastest change just to make sure my db schemes are the latest

**Comment by ruanwenjun** [comment]
@EricPyZhou There miss some ddl sql in `upgrade` sql file. You can just use `dolphinscheduler_mysql.sql` to create the latest schema. If you have time, you can create a new issue to fix the ddl sql.

**Comment by EricPyZhou** [comment]
> @EricPyZhou There miss some ddl sql in `upgrade` sql file. You can just use `dolphinscheduler_mysql.sql` to create the latest schema. If you have time, you can create a new issue to fix the ddl sql.

I don't really find any dolphinscheduler_mysql.sql under sql directory. Is there another sql file I should use to get the latest schema? Or I can just run UpgradeDolphinScheduler in DAO module

For the ddl sql in sql/upgrade directory, which version of schema are we using in dev branch. I checked the version in the root ppm.xml, but it says 2.0 SNAPSHOT,  which can not be associated to any version under the upgrade directory

**Comment by ruanwenjun** [comment]
@EricPyZhou https://github.com/apache/dolphinscheduler/tree/dev/sql

**Comment by EricPyZhou** [comment]
> @EricPyZhou https://github.com/apache/dolphinscheduler/tree/dev/sql

I'll look at the implementation in more details. This link is honestly not that helpful...

**Comment by ruanwenjun** [comment]
@EricPyZhou Can you find this file?
![image](https://user-images.githubusercontent.com/22415594/135034701-67d15c0b-0310-4c4c-80d1-a42ea1871cc3.png)

**Comment by EricPyZhou** [comment]
> @EricPyZhou Can you find this file?
> ![image](https://user-images.githubusercontent.com/22415594/135034701-67d15c0b-0310-4c4c-80d1-a42ea1871cc3.png)
> 

Oh Yes. I didn't see it. For some reason, it didn't pop up in the search result on Github. My bad.

**Comment by EricPyZhou** [comment]
> @EricPyZhou Can you find this file?
> ![image](https://user-images.githubusercontent.com/22415594/135034701-67d15c0b-0310-4c4c-80d1-a42ea1871cc3.png)

To update the database, do I just run sh ./script/upgrade-dolphinscheduler like in this instruction: https://dolphinscheduler.apache.org/en-us/docs/1.3.2/user_doc/upgrade.html?

**Comment by EricPyZhou** [comment]
Updates on this issue. @ruanwenjun 
1. tests are all failed at line 69 because the processInstance object here does not have the attribute `processDefinitionCode`, and the field `process_definition_code` is NOT NULL. Therefore my solution is to add the default value to the field.
![image](https://user-images.githubusercontent.com/26387900/135373182-df7b81aa-7bf4-400b-a645-1cf24a84b513.png)

2. I am not sure where to put  
SQL ALTER TABLE t_ds_process_instance MODIFY COLUMN `process_definition_code` bigint(20) not NULL COMMENT 'process definition code' AFTER `worker_group`;
Should I put it into sql/upgrade/1.4.0_scheme/mysql/dolphinscheduler_ddl.sql? or just modify directly in dolphinscheduler_mysql.sql?
![image](https://user-images.githubusercontent.com/26387900/135373806-cd636183-8a43-4e66-833c-a79b4c4ef67b.png)

**Comment by ruanwenjun** [comment]
@EricPyZhou You shouldn't modify the sql file, you just need to fix this UT, right?
There are two problems.

**Comment by EricPyZhou** [comment]
> @EricPyZhou You shouldn't modify the sql file, you just need to fix this UT, right? There are two problems.

This is a quick fix, how do you find it? @ruanwenjun 
![image](https://user-images.githubusercontent.com/26387900/135377453-415a3021-2ccf-484d-857f-981a986ede83.png)

PS: If I create a new issue to modify the ddl sql (gives `process_definition_code` a default value), this UT can be resolved automatically without any change. But, I am not sure if this modification is aligned with the original design idea.

**Comment by EricPyZhou** [comment]
> > @EricPyZhou You shouldn't modify the sql file, you just need to fix this UT, right? There are two problems.
> 
> This is a quick fix to pass all tests, how do you find it? @ruanwenjun ![image](https://user-images.githubusercontent.com/26387900/135377453-415a3021-2ccf-484d-857f-981a986ede83.png)
> 
> But if I create a new issue to fix the ddl sql issue, this UT can be resolved automatically without any change.

**Comment by ruanwenjun** [comment]
@EricPyZhou Of course, you can fix the sql file, but you need to make sure this change is accepted by the community. I remember there was a pr has discussed the default value, you can find.

**Comment by EricPyZhou** [comment]
> @EricPyZhou Of course, you can fix the sql file, but you need to make sure this change is accepted by the community. I remember there was a pr has discussed the default value, you can find.

I will give it a look. Thanks!

**Comment by EricPyZhou** [comment]
> @EricPyZhou Of course, you can fix the sql file, but you need to make sure this change is accepted by the community. I remember there was a pr has discussed the default value, you can find.

@ruanwenjun From what I read from here:
api模块进行save操作时

通过雪花算法生成13位的数字作为process_definition_code，工作流定义保存至process_definition（主表）和process_definition_log（日志表），这两个表保存的是同样的数据，工作流定义版本为1

作者：政采云大数据团队
链接：https://juejin.cn/post/7004640905806217252
来源：稀土掘金

I think I can just use the quick fix in `before` in `TaskInstanceMapperTest` (manually set `process_definition_code` ) because there is essentially no need to give it a default value when the definition code can be generated by the snowflake algorithm every time a workflow is saved

**Comment by ruanwenjun** [comment]
@EricPyZhou I think your plan is OK.

**Comment by EricPyZhou** [comment]
@ruanwenjun Can you help review this PR. Thank you
