### ISSUE TITLE
[Bug] [server]  Why getPidStr by pstree only get child process

### ISSUE THREAD

**Issue by xtr1993** [apache/dolphinscheduler#7578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a question about dolphinscheduler-server module

please see org.apache.dolphinscheduler.server.utils.ProcessUtils 173 line

`
if (CommonUtils.isSudoEnable() && !pidList.isEmpty()) {
            pidList = pidList.subList(1, pidList.size());
        }
`

when sudo.enable pidList from 1 and pidList.size?
why use this way? 
maybe only get child process and lost parents process

### What you expected to happen

I think should this is unnecessary

### How to reproduce

please see org.apache.dolphinscheduler.server.utils.ProcessUtils 173 line

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
1. Dolphin will first start a sudo root process
2. When kill, kill all child processes, the sudo process will also end
3. For this piece, why remove the first pid, because the first pid is a root-level process 

```java
  pidList = pidList.subList(1, pidList.size());
```
When using sudo -u tenant kill -9 pids, it will report insufficient permissions. If this is changed to sudo kill -9 pids, there is no need to remove the first pid above.
