### ISSUE TITLE
[Bug] [MasterServer] Submit  duplicate tasks

### ISSUE THREAD

**Issue by mchcz** [apache/dolphinscheduler#7788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Many SQL tasks submitted at the same time
2.It will be retried when a task fails, and may be submitted multiple times when retrying
3.The task instance code is the same for multiple submissions

[INFO] 2022-01-04 00:50:34.791 org.apache.dolphinscheduler.service.process.ProcessService:[1076] - end submit task to db successfully:6838135 013.XXX:SUBMITTED_SUCCESS complete, instance id:609369 state: RUNNING_EXECUTION
[INFO] 2022-01-04 00:50:35.315 org.apache.dolphinscheduler.service.process.ProcessService:[1076] - end submit task to db successfully:6838145 013.XXX:SUBMITTED_SUCCESS complete, instance id:609369 state: RUNNING_EXECUTION 

![image](https://user-images.githubusercontent.com/18095523/148180811-2836c795-6bc1-4503-9092-ef3f20491a88.png)

![image](https://user-images.githubusercontent.com/18095523/148180849-6d4080be-b266-4e0e-a39d-dade8ed517cf.png)

![image](https://user-images.githubusercontent.com/18095523/148180902-4ce5934b-093d-48fd-a78b-998248cdec47.png)

### What you expected to happen

When the task is retried, submit it once.

### How to reproduce

The reason is unknown.

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
@mchcz can you provide the DAG info? I can't reproduce it at local.

**Comment by caishunfeng** [comment]
![image](https://user-images.githubusercontent.com/11962619/148408795-af6bbe70-01d3-478c-8a85-a83ed5091263.png)
![image](https://user-images.githubusercontent.com/11962619/148408951-9cb93aba-d4c1-41b1-9f43-978c981f64c0.png)
![454387769cb60b28eb72a754c53d6aa](https://user-images.githubusercontent.com/11962619/148407707-67564c2a-8920-4f28-af43-e97dfde6414b.png)
![698ec6741cfcebde7574d277fce2602](https://user-images.githubusercontent.com/11962619/148407751-8c127c2d-6bf0-4be7-87c3-d6b9c6ffd508.png)

When task A fail and run `WorkflowExecuteThread.taskFinished`, it will add retry task into standby queue, which will submit by `WorkflowExecuteThread.submitPostNode` and `StateWheelExecuteThread.checkTask4Retry`;  When I add sleep 30s in `submitTaskInstanceToDB` like Figure 4, it will increase the probability of repeated retries. In this way, retry task A in standby list will be submit by `WorkflowExecuteThread.submitPostNode` because run task c, and then, `StateWheelExecuteThread.checkTask4Retry` add it into standby list and submit again.
