### ISSUE TITLE
[Feature][dolphinscheduler-server]  master and worker  network interaction

### ISSUE THREAD

**Issue by zwZjut** [apache/dolphinscheduler#8052]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Feature][dolphinscheduler-server]  master and worker  Network interaction : 3 time->2 time

### Use case

[Feature][dolphinscheduler-server]  master and worker  Network interaction : 3 time->2 time

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
improvements:
- network interactions (normal/abnormal)  
- use async send instead of sync
- retry strategy (now we use cache list everywhere, maybe it should sink to the communication layer)

**Comment by caishunfeng** [comment]
![task_network_interaction](https://user-images.githubusercontent.com/11962619/150123559-b7facb09-482c-4d88-9574-fbc531761763.png)

I found some optimization of task network interaction:
1. worker use a unified task cache in memory, and reply looply in a interval if task change.
2. each time the worker reply task with the whole task info and version, so that master can ignore the low version when the high version task info arrive early.
