### ISSUE TITLE
[Bug-RD][UI Next][V1.0.0-Alpha]lick a scheduled task, a message is displayed indicating that the scheduled task fails

### ISSUE THREAD

**Issue by XuXuClassMate** [apache/dolphinscheduler#8800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you click a scheduled task, a message is displayed indicating that the scheduled task fails
error message:publish schedule online error

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/76080484/157586418-108cd1c0-f2e1-44c7-950b-77d87c87973e.png">

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/76080484/157586504-00115604-5a22-4b57-a5a4-4e4123ff58fd.png">

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/76080484/157586782-bf7d6a41-1c0f-4d85-8652-108aed0ccf33.png">

### What you expected to happen

The scheduled task starts normally

### How to reproduce

1. Online workflow
2. Set a scheduled task
3. Perform scheduled task online operations

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have debug the code, the problem which I found is.

**Comment by Tianqi-Dotes** [comment]
I have debugged the code, the problem which I found is.
1. endtime is before starttime, so that the quartz cannot submit the task
2. after I adjust the endtime, the program still can't execute, and the problem is:
![image](https://user-images.githubusercontent.com/36755957/158066046-6d0b43f2-0baf-4f1d-bf0e-09df95513009.png)
The query SQL is ,
UPDATE t_ds_schedules SET warning_type=0, environment_code=-1, crontab='* * 1/11 * * ? *', warning_group_id=0, update_time='2022-03-13 21:28:43.0', user_id=1, process_definition_code=4793853346624, failure_strategy=1, create_time='2022-03-10 11:40:45.0', timezone_id='Asia/Shanghai', start_time='2022-03-10 08:00:00.0', worker_group='default', release_state=1, end_time='2022-03-10 09:00:00.0', process_instance_priority=2 WHERE id=2;
The lock query is :
SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'DolphinScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE

So that's what I found.

**Comment by Tianqi-Dotes** [comment]
But this time I changed the endtime to 2022-03-10 12:00:00, it runs well.

**Comment by Tianqi-Dotes** [comment]
I guess the problem is :
1. endtime before starttime.
2. At that time, the table is locked for update leads to some quartz issues.
