### ISSUE TITLE
[Bug] [Server] UT failed in LoggerServer 

### ISSUE THREAD

**Issue by EricJoy2048** [apache/dolphinscheduler#8972]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

UT failed in LoggerServer `LoggerServerTest`.

### What you expected to happen

UT success.

### How to reproduce

fix the UT code.

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tianqi-Dotes** [comment]
I have checked this issue and found the 'testRemoveTaskLog' UT method throw an exception but UT is successful on my local machine.
The method has the following functions:
1. Create a file '\tmp\remove.log'.
2. Call method 'logClientService.removeTaskLog' to delete the log.
3. Read the file and view the log.
The question is the 3rd step, the file has already been deleted so that throw a 'FileNotFoundException' and cause a logger print 'ERROR' log. I think this one is fine, it is reasonable and the UT result is successful.

![image](https://user-images.githubusercontent.com/36755957/158965473-bf0ce4fe-88c2-4429-9ba7-ad869d330d9c.png)

**Comment by EricJoy2048** [comment]
> have checked this issue and found the 'testRemoveTaskLog' UT method throw an exception but UT is successful on my local machine. The method has the following functions:
> 
> 1. Create a file '\tmp\remove.log'.
> 2. Call method 'logClientService.removeTaskLog' to delete the log.
> 3. Read the file and view the log.
>    The question is the 3rd step, the file has already been deleted so that throw a 'FileNotFoundException' and cause a logger print 'ERROR' log. I think this one is fine, it is reasonable and the UT result is successful.

So, Is there a problem here? Do I need to modify it ？
