### ISSUE TITLE
[Bug] [UI]  Dev branch, the navigation bar of the front page is not fully displayed

### ISSUE THREAD

**Issue by BoYiZhang** [apache/dolphinscheduler#9282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dev branch, the navigation bar of the front page is not fully displayed

![image](https://user-images.githubusercontent.com/39816903/160786451-34c39412-9ba9-473c-a375-cda3a5d5338a.png)

### What you expected to happen

The navigation bar is displayed normally

### How to reproduce

Change the display mode, and some functions support hiding

### Anything else

nothing

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caishunfeng** [comment]
PTAL @songjianet

**Comment by EricGao888** [comment]
> PTAL @songjianet

@caishunfeng @BoYiZhang I think this issue has been fixed by https://github.com/apache/dolphinscheduler/pull/9264

I just double-checked the dev branch code. It looked good. 
![image](https://user-images.githubusercontent.com/34905992/161371557-7a6598ba-ac71-479a-a85c-925840f2ae38.png)

**Comment by czeming** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> Dev branch, the navigation bar of the front page is not fully displayed
> 
> ![image](https://user-images.githubusercontent.com/39816903/160786451-34c39412-9ba9-473c-a375-cda3a5d5338a.png)
> 
> ### What you expected to happen
> The navigation bar is displayed normally
> 
> ### How to reproduce
> Change the display mode, and some functions support hiding
> 
> ### Anything else
> nothing
> 
> ### Version
> dev
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

I hope I can help you solve this problem, but I think it should be caused by the difference of display screen.
The pixel critical point that triggers the problem is `1476px / 1477px`.

`body.width<=1476px`
![](https://s2.loli.net/2022/04/02/z43rXYpNoiAuydl.png)

`body.width>=1477px`
![](https://s2.loli.net/2022/04/02/AntVscIbefGgFM3.png)

or you want a responsive layout, where the extra navigation bar is hidden into more buttons when the screen width is not enough (it may involve the design style of dolphin scheduler).


Here are three possible approaches:

1. Maintain the status quo

2. Agreed minimum compatible resolution value

3. Responsive layout, that is, more buttons mentioned above. When the mouse moves to more, the hidden navigation menu will be displayed, but it needs to be discussed clearly how to display the above navigation bar when jumping to the corresponding interface of the hidden navigation. If it is still hidden, the page will look disconnected from the navigation. (not recommended)

@songjianet
