### ISSUE TITLE
[Bug][Recover Suspend] Process Instance directly changed to success when click 'Recovery Suspend'

### ISSUE THREAD

**Issue by reele** [apache/dolphinscheduler#9679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

A Process Instance failed by some subprocess's failure, click `Recovery Suspend` then main process instance's state changed to `success` and subprocess's state changed to `submitted`, and there's no more actions after that....

### What you expected to happen

should restart the failed task

### How to reproduce

when some subprocess in process, and subprocess failed.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by labbomb** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/15062456/164953730-8400bd82-b7a9-481d-a51f-aecae96ac2c2.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/15062456/164953784-4e7c8715-581b-4328-ba02-7e47f8c1ca84.png">
When the workflow restarts due to an interruption or failure, the front end simply rerequests and refreshes the list
