### ISSUE TITLE
[Feature][Task-plugin] Add OpenMLDB task-plugin

### ISSUE THREAD

**Issue by vagetablechicken** [apache/dolphinscheduler#9950]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I want to add the OpenMLDB task-plugin to support run cmds on OpenMLDB. 
There're some ways to impl it.
1. If we impl it like zeppelin, we'll add openmldb jdbc dependency. openmldb jdbc will use openmldb-native jar which has c++ shared lib in it. The released package will contain it. [openmldb-native jar is 156.9MB](https://mvnrepository.com/artifact/com.4paradigm.openmldb/openmldb-native/0.5.0-allinone), a little big.
2. If we impl it like datax or python task, we can let users to install openmldb python sdk later, won't add it in releases. And python wheel is smaller. [23MB](https://pypi.org/project/openmldb/#files)

Plz help me decide on which way to impl the task.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Hi @vagetablechicken , it is welcome to add any task to DolphinScheduler, but this case it is a little different because the java SDK for OpenMLDB is a little big IMO. After we release version 3.0.0-alpha, we find out some of our users complain about the size of our tarball. and we have created some issues and do some effort to slim our binary package which you can see in #9813 and #9843.

So If those are the only two ways to add OpenMLDB task to DolphinScheduler, I prefer the second way, because it will not make our tarball too large. But it have to ask users to do more prepare job before they user OpenMLDB(which not out-of-box). WDYT @caishunfeng @lenboo @zhuangchong @SbloodyS

**Comment by SbloodyS** [comment]
> Hi @vagetablechicken , it is welcome to add any task to DolphinScheduler, but this case it is a little different because the java SDK for OpenMLDB is a little big IMO. After we release version 3.0.0-alpha, we find out some of our users complain about the size of our tarball. and we have created some issues and do some effort to slim our binary package which you can see in #9813 and #9843.
> 
> So If those are the only two ways to add OpenMLDB task to DolphinScheduler, I prefer the second way, because it will not make our tarball too large. But it have to ask users to do more prepare job before they user OpenMLDB(which not out-of-box). WDYT @caishunfeng @lenboo @zhuangchong @SbloodyS

Agreed.
